---
title: "Example Usage (Panel Data)"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


## Load Sample Data


```{r}
# load package
require(DIDdesign)

# load sample data
data("anzia2012")

```


## Visualizing Data

```{r}
# original series 
did_plot(lnavgsalary_cpi ~ oncycle, data = anzia2012,
  post_treatment = c(2007, 2008, 2009),
  id_subject = "district",
  id_time = "year",
  ylim = c(10.55, 10.8),
  diff_order = 0,
  main = 'Original Series'
)

# differenced series (changes-in-trend)
did_plot(lnavgsalary_cpi ~ oncycle, data = anzia2012,
  post_treatment = c(2007, 2008, 2009),
  id_subject = "district",
  id_time = "year",
  ylim = c(-0.05, 0.05),
  diff_order = 1,
  main = 'Differenced Series'
)
```

## Nonparametric Estimator


```{r}
# estimate ATT
fit_np <- did(lnavgsalary_cpi ~ oncycle, data = anzia2012,
	id_subject = "district", id_time = "year",
	post_treatment = c(2007, 2008, 2009),
	method = "nonparametric",
	se_boot = FALSE
)

# summary function
summary(fit_np)


# plot results
plot(fit_np, full = TRUE)
```


## Parametric Estimator (with Covariates)

```{r}
fit_p1 <- did(lnavgsalary_cpi ~ oncycle | teachers_avg_yrs_exper +
						ami_pc + asian_pc + black_pc + hisp_pc,
  data = anzia2012, id_subject = 'district', id_time = 'year',
  post_treatment = c(2007, 2008, 2009),
	method = 'parametric')
```
```{r}
# summary function
summary(fit_p1)

# plot function
plot(fit_p1, full = TRUE, ylim = c(-0.025, 0.005), xlim = c(-0.5, 3.5))
abline(h = 0, col = 'gray', lwd = 1.5, lty = 3)
```


We can compare estimates from a model without covariates.

```{r}
fit_p2 <- did(lnavgsalary_cpi ~ oncycle, data = anzia2012,
	id_subject = "district", id_time = "year",
	post_treatment = c(2007, 2008, 2009),
	method = "parametric")

```


```{r}
# summary function
summary(fit_p2)

# plot function
par(mfrow = c(1,2), mar = c(4, 2.5, 3.5, 1))
plot(fit_p1, full = TRUE, ylim = c(-0.025, 0.005), xlim = c(-0.5, 3.5), main = "With Covariates")
abline(h = 0, col = 'gray', lwd = 1.5, lty = 3)
plot(fit_p2, full = TRUE, ylim = c(-0.025, 0.005), xlim = c(-0.5, 3.5), main = 'Without Covariates')
abline(h = 0, col = 'gray', lwd = 1.5, lty = 3)
```
