
---
title: "Getting Started"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


## Design of this package 

`DIDdesign` is developed to implement double difference-in-differeces method 
and also to diagnose difference-in-differences design in general.


It is designed that users implement main functions in the following order:

### 1 `did_plot()`:visual assessment of DiD design

+ `diff_order` argument allows users to plot the mean outcome (`diff_order = 0`) and the mean outcome of differenced series (`diff_order = 1`). 
+ `ci = TRUE` shows confidence intervals (the level of confidence intervels is controlled by `alpha`).

### 2 `did()`: estimation of treatment effects

+ `formula` input allows flexible inputs such as time-varying covariates by `y ~ treatment | x1 + as.factor(x2)` for example. 
+ This function supports two main estimators `method = "parametric"` fit parametric model similar to the two-way fixed effect model. Parametric model allows inclusion of time-varying covariates. `method = nonparametric` implements moment based estimator.

### 3 `summary.diddesign()` and `plot.diddesign()`: presentation of results

+ Both functions are S3 object, so users can simply use them by `summary()` and `plot()`.
+ Both function shows results from the selected models by default. `full = TRUE` option allows users to check all estimates. 

### 4 `did_plot_selection()`: 
