// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// loss_loop
arma::mat loss_loop(const arma::mat& X, const arma::vec& y, const arma::vec& par, const arma::uvec& id_subject, const arma::uvec& uid, const arma::uvec& is_na, const int& nobs, const int& p);
RcppExport SEXP _DIDdesign_loss_loop(SEXP XSEXP, SEXP ySEXP, SEXP parSEXP, SEXP id_subjectSEXP, SEXP uidSEXP, SEXP is_naSEXP, SEXP nobsSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type par(parSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type id_subject(id_subjectSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type uid(uidSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type is_na(is_naSEXP);
    Rcpp::traits::input_parameter< const int& >::type nobs(nobsSEXP);
    Rcpp::traits::input_parameter< const int& >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(loss_loop(X, y, par, id_subject, uid, is_na, nobs, p));
    return rcpp_result_gen;
END_RCPP
}
// rcs_mean_fill
Rcpp::List rcs_mean_fill(const arma::vec& outcome, const arma::ivec& treatment, const arma::uvec& time_index, const arma::uvec& time_unique, const arma::rowvec& y1mean, const arma::rowvec& y0mean);
RcppExport SEXP _DIDdesign_rcs_mean_fill(SEXP outcomeSEXP, SEXP treatmentSEXP, SEXP time_indexSEXP, SEXP time_uniqueSEXP, SEXP y1meanSEXP, SEXP y0meanSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type outcome(outcomeSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type treatment(treatmentSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type time_index(time_indexSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type time_unique(time_uniqueSEXP);
    Rcpp::traits::input_parameter< const arma::rowvec& >::type y1mean(y1meanSEXP);
    Rcpp::traits::input_parameter< const arma::rowvec& >::type y0mean(y0meanSEXP);
    rcpp_result_gen = Rcpp::wrap(rcs_mean_fill(outcome, treatment, time_index, time_unique, y1mean, y0mean));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_DIDdesign_loss_loop", (DL_FUNC) &_DIDdesign_loss_loop, 8},
    {"_DIDdesign_rcs_mean_fill", (DL_FUNC) &_DIDdesign_rcs_mean_fill, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_DIDdesign(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
