# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' helper function for the loss computation 
#' @useDynLib DIDdesign
loss_loop <- function(X, y, par, id_subject, uid, is_na, nobs, p) {
    .Call('_DIDdesign_loss_loop', PACKAGE = 'DIDdesign', X, y, par, id_subject, uid, is_na, nobs, p)
}

