# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' helper function for the loss computation
#' @useDynLib DIDdesign
#' @keywords internal
loss_loop <- function(X, y, par, id_subject, uid, is_na, nobs, p) {
    .Call('_DIDdesign_loss_loop', PACKAGE = 'DIDdesign', X, y, par, id_subject, uid, is_na, nobs, p)
}

#' helper function for repeated cross-section data
#' @param outcome outcome vector
#' @param treatment treatment vector
#' @param time_index time id for each unit
#' @param time_unique a vector of unique time index (should be increasing order)
#' @param y1mean a vector of mean outcome for the treated
#' @param y0mean a vector of mean outcome for the control
#' @value a matrix of outcome filled with mean outcome for each group
#' @keywords internal
rcs_mean_fill <- function(outcome, treatment, time_index, time_unique, y1mean, y0mean) {
    .Call('_DIDdesign_rcs_mean_fill', PACKAGE = 'DIDdesign', outcome, treatment, time_index, time_unique, y1mean, y0mean)
}

